### ISSUE TITLE
 2024.4.1b0 - Component fails to setup 

### ISSUE THREAD

**Issue by collse** [pantherale0/haanglianwater#12]
## System Information

version | core-2024.4.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.6.25-haos
arch | x86_64
timezone | Europe/London
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4649
Installed Version | 1.34.0
Stage | running
Available Repositories | 1403
Downloaded Repositories | 61

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.2
-- | --
update_channel | stable
supervisor_version | supervisor-2024.04.0
agent_version | 1.6.0
docker_version | 25.0.5
disk_total | 109.3 GB
disk_used | 43.6 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Samba share (12.3.1), Duck DNS (1.16.0), File editor (5.8.0), Glances (0.21.1), Log Viewer (0.17.0), Advanced SSH & Web Terminal (17.2.0), MariaDB (2.7.1), Vaultwarden (Bitwarden) (0.21.2), chrony (3.0.1), Samba Backup (5.2.0), Z-Wave JS UI (3.5.0), Zigbee2MQTT (1.36.1-1), Mosquitto broker (6.4.0), Nginx Proxy Manager (1.0.1), Studio Code Server (5.15.0), ESPHome (2024.4.0), Govee to MQTT Bridge (2024.01.24-ea3cd430)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 53
views | 12
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 19 April 2024 at 14:57
-- | --
current_recorder_run | 22 April 2024 at 13:48
estimated_db_size | 831.50 MiB
database_engine | mysql
database_version | 10.11.6

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

The component now fails to setup 2024.4.1b0.

> 2024-04-22 13:48:57.336 INFO (SyncWorker_2) [homeassistant.util.package] Attempting install of pyanglianwater==0.2.1
> 2024-04-22 13:49:05.014 INFO (MainThread) [homeassistant.setup] Setting up anglian_water
> 2024-04-22 13:49:06.005 DEBUG (MainThread) [pyanglianwater.api] >> Request to login successful.
> 2024-04-22 13:49:08.613 DEBUG (MainThread) [pyanglianwater.api] >> Request to get_bills_payments successful.
> 2024-04-22 13:49:10.225 DEBUG (MainThread) [pyanglianwater.api] >> Request to get_usage_details successful.
> 2024-04-22 13:49:12.321 DEBUG (MainThread) [pyanglianwater.api] >> Request to get_usage_details successful.
> 2024-04-22 13:49:12.323 ERROR (MainThread) [custom_components.anglian_water] Unexpected error fetching anglian_water data: 0
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 315, in _async_refresh
>     self.data = await self._async_update_data()
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/anglian_water/coordinator.py", line 63, in _async_update_data
>     await self._insert_statistics()
>   File "/config/custom_components/anglian_water/coordinator.py", line 100, in _insert_statistics
>     hourly_consumption_data[0]["meterReadTimestamp"]
>     ~~~~~~~~~~~~~~~~~~~~~~~^^^
> KeyError: 0
> 2024-04-22 13:49:12.337 DEBUG (MainThread) [custom_components.anglian_water] Finished fetching anglian_water data in 6.330 seconds (success: False)
> 2024-04-22 13:49:18.693 DEBUG (MainThread) [pyanglianwater.api] >> Request to login successful.
> 2024-04-22 13:49:21.412 DEBUG (MainThread) [pyanglianwater.api] >> Request to get_bills_payments successful.
> 2024-04-22 13:49:23.065 DEBUG (MainThread) [pyanglianwater.api] >> Request to get_usage_details successful.
> 2024-04-22 13:49:24.862 DEBUG (MainThread) [pyanglianwater.api] >> Request to get_usage_details successful.
> 2024-04-22 13:49:24.866 ERROR (MainThread) [custom_components.anglian_water] Unexpected error fetching anglian_water data: 0
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 315, in _async_refresh
>     self.data = await self._async_update_data()
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/anglian_water/coordinator.py", line 63, in _async_update_data
>     await self._insert_statistics()
>   File "/config/custom_components/anglian_water/coordinator.py", line 100, in _insert_statistics
>     hourly_consumption_data[0]["meterReadTimestamp"]
>     ~~~~~~~~~~~~~~~~~~~~~~~^^^
> KeyError: 0
> 2024-04-22 13:49:24.868 DEBUG (MainThread) [custom_components.anglian_water] Finished fetching anglian_water data in 6.172 seconds (success: False)
> 

### Reproduction steps

1. install 2024.4.1b0
2. enable debugging
3. recreate the integration
4. select water tariff "standard'
5. add custom water rate float - eg 194
6. component confirms "Success" but the integration reports: failed setup, will retry
...

### Debug logs

```text
2024-04-22 13:49:05.014 INFO (MainThread) [homeassistant.setup] Setting up anglian_water
2024-04-22 13:49:06.005 DEBUG (MainThread) [pyanglianwater.api] >> Request to login successful.
2024-04-22 13:49:08.613 DEBUG (MainThread) [pyanglianwater.api] >> Request to get_bills_payments successful.
2024-04-22 13:49:10.225 DEBUG (MainThread) [pyanglianwater.api] >> Request to get_usage_details successful.
2024-04-22 13:49:12.321 DEBUG (MainThread) [pyanglianwater.api] >> Request to get_usage_details successful.
2024-04-22 13:49:12.323 ERROR (MainThread) [custom_components.anglian_water] Unexpected error fetching anglian_water data: 0
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 315, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/anglian_water/coordinator.py", line 63, in _async_update_data
    await self._insert_statistics()
  File "/config/custom_components/anglian_water/coordinator.py", line 100, in _insert_statistics
    hourly_consumption_data[0]["meterReadTimestamp"]
    ~~~~~~~~~~~~~~~~~~~~~~~^^^
KeyError: 0
2024-04-22 13:49:12.337 DEBUG (MainThread) [custom_components.anglian_water] Finished fetching anglian_water data in 6.330 seconds (success: False)
2024-04-22 13:49:18.693 DEBUG (MainThread) [pyanglianwater.api] >> Request to login successful.
2024-04-22 13:49:21.412 DEBUG (MainThread) [pyanglianwater.api] >> Request to get_bills_payments successful.
2024-04-22 13:49:23.065 DEBUG (MainThread) [pyanglianwater.api] >> Request to get_usage_details successful.
2024-04-22 13:49:24.862 DEBUG (MainThread) [pyanglianwater.api] >> Request to get_usage_details successful.
2024-04-22 13:49:24.866 ERROR (MainThread) [custom_components.anglian_water] Unexpected error fetching anglian_water data: 0
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 315, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/anglian_water/coordinator.py", line 63, in _async_update_data
    await self._insert_statistics()
  File "/config/custom_components/anglian_water/coordinator.py", line 100, in _insert_statistics
    hourly_consumption_data[0]["meterReadTimestamp"]
    ~~~~~~~~~~~~~~~~~~~~~~~^^^
KeyError: 0
2024-04-22 13:49:24.868 DEBUG (MainThread) [custom_components.anglian_water] Finished fetching anglian_water data in 6.172 seconds (success: False)
```

**Comment by pantherale0** [comment]
Thanks.

Note the custom water rate will only be used if you select the "LITE" tariff, otherwise it will always use the tariff information published on the website (https://www.anglianwater.co.uk/services/extra-support/tariff-options/standard-rates/) - also, rates should be specified in £ (eg `2.0954` rather than `20954`)

**Comment by collse** [comment]
thanks @pantherale0 this makes sense now - I only added 194 as it seemed the input marks 1.94 in red, if I recall correctly but subsequent tests showed it still accept it

**Comment by strickersuk** [comment]
Same for me, expected float when selecting standard rate.

**Comment by collse** [comment]
> Same for me, expected float when selecting standard rate.

just add anything it wont take the custom water rate anyway when selecting standard
