### ISSUE TITLE
Inconsistent readings - data does not align with Anglians data set

### ISSUE THREAD

**Issue by collse** [pantherale0/haanglianwater#13]
## System Information

version | core-2024.4.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.6.25-haos
arch | x86_64
timezone | Europe/London
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4679
Installed Version | 1.34.0
Stage | running
Available Repositories | 1403
Downloaded Repositories | 61

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.2
-- | --
update_channel | stable
supervisor_version | supervisor-2024.04.0
agent_version | 1.6.0
docker_version | 25.0.5
disk_total | 109.3 GB
disk_used | 43.9 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Samba share (12.3.1), Duck DNS (1.17.0), File editor (5.8.0), Glances (0.21.1), Log Viewer (0.17.0), Advanced SSH & Web Terminal (17.2.0), MariaDB (2.7.1), Vaultwarden (Bitwarden) (0.21.2), chrony (3.0.1), Samba Backup (5.2.0), Z-Wave JS UI (3.5.0), Zigbee2MQTT (1.36.1-1), Mosquitto broker (6.4.0), Nginx Proxy Manager (1.0.1), Studio Code Server (5.15.0), ESPHome (2024.4.1), Govee to MQTT Bridge (2024.01.24-ea3cd430)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 53
views | 12
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 24 April 2024 at 10:33
-- | --
current_recorder_run | 26 April 2024 at 12:43
estimated_db_size | 837.17 MiB
database_engine | mysql
database_version | 10.11.6

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

The data shown on the sensor as well the energy dashboard does not align with the data shown in Anglians dashboard.

April 25th data in HA
![image](https://github.com/pantherale0/haanglianwater/assets/5358625/cdb384ee-0ecf-418d-8d9f-9c1634d1bb83)

Sensor
![image](https://github.com/pantherale0/haanglianwater/assets/5358625/203a8e1b-88ef-4706-af34-25e417eb625d)

Anglian webUI
![image](https://github.com/pantherale0/haanglianwater/assets/5358625/2124bff6-59d3-4674-b192-6130a24faa10)

![image](https://github.com/pantherale0/haanglianwater/assets/5358625/58a9704d-a09a-450c-9704-97e4eeb4e1b4)

### Reproduction steps

1. enable component
2. compare previous day data with Anglians webinterface
...

### Debug logs

```text
no errors in the logs 

collections are all with:
 [custom_components.anglian_water] Finished fetching anglian_water data in x.xx seconds (success: True)
```

**Comment by collse** [comment]
interestingly I just had an error come up:
2024-04-26 14:04:10.212 ERROR (MainThread) [pyanglianwater.api] >> Error sending request get_usage_details to Anglian Water (401) - {"Message":"Unauthorized"}
2024-04-26 14:04:11.274 DEBUG (MainThread) [pyanglianwater.api] >> Request to login successful.
2024-04-26 14:04:12.994 DEBUG (MainThread) [pyanglianwater.api] >> Request to get_usage_details successful.
2024-04-26 14:04:14.864 DEBUG (MainThread) [pyanglianwater.api] >> Request to get_usage_details successful.
2024-04-26 14:04:14.869 DEBUG (MainThread) [custom_components.anglian_water] Finished fetching anglian_water data in 4.776 seconds (success: True)

but the connection still claimed to be successful

**Comment by pantherale0** [comment]
Thats interesting, the data comes direct from AW, and the integration doesn't really muddle with any of the data either. In fact you can see the function here (https://github.com/pantherale0/pyanglianwater/blob/c5c1b939094c23c9c9d6fd0de18c679b3c233a70/pyanglianwater/__init__.py#L23)

What it does do is take the meter reading (in cubic meters) and divide by 1000 to get the litres consumed which is used as a sum. The value you actually see in the energy dashboard comes from https://github.com/pantherale0/haanglianwater/blob/74b683a9f8fd5a0379ebcb5086ec14d90b6926dc/custom_components/anglian_water/coordinator.py#L112 which doesn't get touched at all.

So its almost like AW are returning two different things for some odd reason. The 401 unauthorized error is nothing to worry about either, the module handles this itself and it was successful as you can see by the lines afterwards.

**Comment by pantherale0** [comment]
Just for the sake of it, I've just compared mine (although against the app) and the readings are fine. Cost isn't but I know why.

![Screenshot_20240426_154418_Home Assistant](https://github.com/pantherale0/haanglianwater/assets/7346615/52100271-a94e-4e86-b4dc-b9ba50e734c4)
![Screenshot_20240426_154324_Anglian Water](https://github.com/pantherale0/haanglianwater/assets/7346615/e8d16c75-cbd4-4ee8-9c58-26c3b67ae068)

**Comment by collse** [comment]
I have tried to adjust the statistic - not sure if this is related to the issue I am seeing:

![image](https://github.com/pantherale0/haanglianwater/assets/5358625/b4f99ba8-878a-4f70-82c8-21f6ec1ace0f)

**Comment by collse** [comment]
is there an option to get a more verbose debug output of the data collection to identify what the problem may be? just thinking out loud to see the collected values?

**Comment by collse** [comment]
I quickly spun up another instance but it inserts the same data so I am not sure where this comes from as it is definitely different to what I see on the app - no idea how to troubleshoot this

**Comment by pantherale0** [comment]
Hmmm this is very weird, I'm not sure whats going on with your account to be honest. If you have the ability to debug, you can use the test script in the module repo, theres no other debug levels available that will spit the data out.

Step into this line:
https://github.com/pantherale0/pyanglianwater/blob/c5c1b939094c23c9c9d6fd0de18c679b3c233a70/test.py#L31C32-L31C47

Then set a breakpoint on this line:

https://github.com/pantherale0/pyanglianwater/blob/c5c1b939094c23c9c9d6fd0de18c679b3c233a70/pyanglianwater/__init__.py#L93

And continue running. When it breaks at this point, the readings are available in `self.current_readings`.

**Comment by pantherale0** [comment]
Actually - overcomplicated that a lot... The test script will print the data it has captured in a dict anyway, so just run it and the data should show in the console.

**Comment by pantherale0** [comment]
> I have tried to adjust the statistic - not sure if this is related to the issue I am seeing:

With this, the HA UI just doesn't like how "accurate" the value is.

**Comment by collse** [comment]
where do I find the device id for the login? I assume I get the wrong one from the core.entity_registry

>> 2024-04-26 22:19:14 pyanglianwater.api DEBUG: >> Request to login successful.
> 2024-04-26 22:19:14 __main__ DEBUG: Logged in. Ready..
> Traceback (most recent call last):
>   File "/home/test.py", line 44, in <module>
>     loop.run_until_complete(main())
>   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 685, in run_until_complete
>     return future.result()
>            ^^^^^^^^^^^^^^^
>   File "/home/test.py", line 31, in main
>     water = await AnglianWater.create_from_api(auth)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/pyanglianwater/__init__.py", line 113, in create_from_api
>     await self.update()
>   File "/usr/local/lib/python3.12/site-packages/pyanglianwater/__init__.py", line 64, in update
>     bills = await self.api.send_request(
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/pyanglianwater/api.py", line 180, in send_request
>     resp_body = await _response.json()
>                 ^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1176, in json
>     raise ContentTypeError(
> aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8', url=URL('https://my.anglianwater.co.uk/mobile/api/GetBillsAndPayments')

**Comment by collse** [comment]
hmm this is strange:

JSON received:

> {'api': <pyanglianwater.api.API object at 0x7f9498c4c080>, 'current_tariff': 'standard', 'current_tariff_rate': 2.0954, 'current_usage': 0.085, 'current_readings': [
> {'contractAccountNumber': '<MASKED>', 'meterReadValue': '11978', 'meterSerialNumber': '<MASKED>', 'ActualMeterSerialNo': '<MASKED>', 'ReadingDate': None, 'ReadingWeekOfYear': None, 'ReadingMonth': 'Apr  2024', 'ReadingMonthOfYear': None, 'meterReadTimestamp': '2024-04-25T00:00:00', 'synthesisedFlag': 'N', 'consumption': 0.0, 'IsSynthesised': False, 'errorCode': 0, 'IsSkipRecord': False}, {'contractAccountNumber': '<MASKED>', 'meterReadValue': '11982', 'meterSerialNumber': '<MASKED>', 'ActualMeterSerialNo': '<MASKED>', 'ReadingDate': None, 'ReadingWeekOfYear': None, 'ReadingMonth': 'Apr  2024', 'ReadingMonthOfYear': None, 'meterReadTimestamp': '2024-04-25T01:00:00', 'synthesisedFlag': 'N', 'consumption': 0.004, 'IsSynthesised': False, 'errorCode': 0, 'IsSkipRecord': False}, {'contractAccountNumber': '<MASKED>', 'meterReadValue': '11982', 'meterSerialNumber': '<MASKED>', 'ActualMeterSerialNo': '<MASKED>', 'ReadingDate': None, 'ReadingWeekOfYear': None, 'ReadingMonth': 'Apr  2024', 'ReadingMonthOfYear': None, 'meterReadTimestamp': '2024-04-25T02:00:00', 'synthesisedFlag': 'N', 'consumption': 0.0, 'IsSynthesised': False, 'errorCode': 0, 'IsSkipRecord': False}, {'contractAccountNumber': '<MASKED>', 'meterReadValue': '11982', 'meterSerialNumber': '<MASKED>', 'ActualMeterSerialNo': '<MASKED>', 'ReadingDate': None, 'ReadingWeekOfYear': None, 'ReadingMonth': 'Apr  2024', 'ReadingMonthOfYear': None, 'meterReadTimestamp': '2024-04-25T03:00:00', 'synthesisedFlag': 'N', 'consumption': 0.0, 'IsSynthesised': False, 'errorCode': 0, 'IsSkipRecord': False}, {'contractAccountNumber': '<MASKED>', 'meterReadValue': '11982', 'meterSerialNumber': '<MASKED>', 'ActualMeterSerialNo': '<MASKED>', 'ReadingDate': None, 'ReadingWeekOfYear': None, 'ReadingMonth': 'Apr  2024', 'ReadingMonthOfYear': None, 'meterReadTimestamp': '2024-04-25T04:00:00', 'synthesisedFlag': 'N', 'consumption': 0.0, 'IsSynthesised': False, 'errorCode': 0, 'IsSkipRecord': False}, {'contractAccountNumber': '<MASKED>', 'meterReadValue': '11982', 'meterSerialNumber': '<MASKED>', 'ActualMeterSerialNo': '<MASKED>', 'ReadingDate': None, 'ReadingWeekOfYear': None, 'ReadingMonth': 'Apr  2024', 'ReadingMonthOfYear': None, 'meterReadTimestamp': '2024-04-25T05:00:00', 'synthesisedFlag': 'N', 'consumption': 0.0, 'IsSynthesised': False, 'errorCode': 0, 'IsSkipRecord': False}, {'contractAccountNumber': '<MASKED>', 'meterReadValue': '11982', 'meterSerialNumber': '<MASKED>', 'ActualMeterSerialNo': '<MASKED>', 'ReadingDate': None, 'ReadingWeekOfYear': None, 'ReadingMonth': 'Apr  2024', 'ReadingMonthOfYear': None, 'meterReadTimestamp': '2024-04-25T06:00:00', 'synthesisedFlag': 'N', 'consumption': 0.0, 'IsSynthesised': False, 'errorCode': 0, 'IsSkipRecord': False}, {'contractAccountNumber': '<MASKED>', 'meterReadValue': '11982', 'meterSerialNumber': '<MASKED>', 'ActualMeterSerialNo': '<MASKED>', 'ReadingDate': None, 'ReadingWeekOfYear': None, 'ReadingMonth': 'Apr  2024', 'ReadingMonthOfYear': None, 'meterReadTimestamp': '2024-04-25T07:00:00', 'synthesisedFlag': 'N', 'consumption': 0.0, 'IsSynthesised': False, 'errorCode': 0, 'IsSkipRecord': False}, {'contractAccountNumber': '<MASKED>', 'meterReadValue': '11982', 'meterSerialNumber': '<MASKED>', 'ActualMeterSerialNo': '<MASKED>', 'ReadingDate': None, 'ReadingWeekOfYear': None, 'ReadingMonth': 'Apr  2024', 'ReadingMonthOfYear': None, 'meterReadTimestamp': '2024-04-25T08:00:00', 'synthesisedFlag': 'N', 'consumption': 0.0, 'IsSynthesised': False, 'errorCode': 0, 'IsSkipRecord': False}, {'contractAccountNumber': '<MASKED>', 'meterReadValue': '11982', 'meterSerialNumber': '<MASKED>', 'ActualMeterSerialNo': '<MASKED>', 'ReadingDate': None, 'ReadingWeekOfYear': None, 'ReadingMonth': 'Apr  2024', 'ReadingMonthOfYear': None, 'meterReadTimestamp': '2024-04-25T09:00:00', 'synthesisedFlag': 'N', 'consumption': 0.0, 'IsSynthesised': False, 'errorCode': 0, 'IsSkipRecord': False}, {'contractAccountNumber': '<MASKED>', 'meterReadValue': '12035', 'meterSerialNumber': '<MASKED>', 'ActualMeterSerialNo': '<MASKED>', 'ReadingDate': None, 'ReadingWeekOfYear': None, 'ReadingMonth': 'Apr  2024', 'ReadingMonthOfYear': None, 'meterReadTimestamp': '2024-04-25T10:00:00', 'synthesisedFlag': 'N', 'consumption': 0.053, 'IsSynthesised': False, 'errorCode': 0, 'IsSkipRecord': False}, {'contractAccountNumber': '<MASKED>', 'meterReadValue': '12036', 'meterSerialNumber': '<MASKED>', 'ActualMeterSerialNo': '<MASKED>', 'ReadingDate': None, 'ReadingWeekOfYear': None, 'ReadingMonth': 'Apr  2024', 'ReadingMonthOfYear': None, 'meterReadTimestamp': '2024-04-25T11:00:00', 'synthesisedFlag': 'N', 'consumption': 0.001, 'IsSynthesised': False, 'errorCode': 0, 'IsSkipRecord': False}, {'contractAccountNumber': '<MASKED>', 'meterReadValue': '12036', 'meterSerialNumber': '<MASKED>', 'ActualMeterSerialNo': '<MASKED>', 'ReadingDate': None, 'ReadingWeekOfYear': None, 'ReadingMonth': 'Apr  2024', 'ReadingMonthOfYear': None, 'meterReadTimestamp': '2024-04-25T12:00:00', 'synthesisedFlag': 'N', 'consumption': 0.0, 'IsSynthesised': False, 'errorCode': 0, 'IsSkipRecord': False}, {'contractAccountNumber': '<MASKED>', 'meterReadValue': '12036', 'meterSerialNumber': '<MASKED>', 'ActualMeterSerialNo': '<MASKED>', 'ReadingDate': None, 'ReadingWeekOfYear': None, 'ReadingMonth': 'Apr  2024', 'ReadingMonthOfYear': None, 'meterReadTimestamp': '2024-04-25T13:00:00', 'synthesisedFlag': 'N', 'consumption': 0.0, 'IsSynthesised': False, 'errorCode': 0, 'IsSkipRecord': False}, {'contractAccountNumber': '<MASKED>', 'meterReadValue': '12036', 'meterSerialNumber': '<MASKED>', 'ActualMeterSerialNo': '<MASKED>', 'ReadingDate': None, 'ReadingWeekOfYear': None, 'ReadingMonth': 'Apr  2024', 'ReadingMonthOfYear': None, 'meterReadTimestamp': '2024-04-25T14:00:00', 'synthesisedFlag': 'N', 'consumption': 0.0, 'IsSynthesised': False, 'errorCode': 0, 'IsSkipRecord': False}, {'contractAccountNumber': '<MASKED>', 'meterReadValue': '12036', 'meterSerialNumber': '<MASKED>', 'ActualMeterSerialNo': '<MASKED>', 'ReadingDate': None, 'ReadingWeekOfYear': None, 'ReadingMonth': 'Apr  2024', 'ReadingMonthOfYear': None, 'meterReadTimestamp': '2024-04-25T15:00:00', 'synthesisedFlag': 'N', 'consumption': 0.0, 'IsSynthesised': False, 'errorCode': 0, 'IsSkipRecord': False}, {'contractAccountNumber': '<MASKED>', 'meterReadValue': '12036', 'meterSerialNumber': '<MASKED>', 'ActualMeterSerialNo': '<MASKED>', 'ReadingDate': None, 'ReadingWeekOfYear': None, 'ReadingMonth': 'Apr  2024', 'ReadingMonthOfYear': None, 'meterReadTimestamp': '2024-04-25T16:00:00', 'synthesisedFlag': 'N', 'consumption': 0.0, 'IsSynthesised': False, 'errorCode': 0, 'IsSkipRecord': False}, {'contractAccountNumber': '<MASKED>', 'meterReadValue': '12036', 'meterSerialNumber': '<MASKED>', 'ActualMeterSerialNo': '<MASKED>', 'ReadingDate': None, 'ReadingWeekOfYear': None, 'ReadingMonth': 'Apr  2024', 'ReadingMonthOfYear': None, 'meterReadTimestamp': '2024-04-25T17:00:00', 'synthesisedFlag': 'N', 'consumption': 0.0, 'IsSynthesised': False, 'errorCode': 0, 'IsSkipRecord': False}, {'contractAccountNumber': '<MASKED>', 'meterReadValue': '12045', 'meterSerialNumber': '<MASKED>', 'ActualMeterSerialNo': '<MASKED>', 'ReadingDate': None, 'ReadingWeekOfYear': None, 'ReadingMonth': 'Apr  2024', 'ReadingMonthOfYear': None, 'meterReadTimestamp': '2024-04-25T18:00:00', 'synthesisedFlag': 'N', 'consumption': 0.009, 'IsSynthesised': False, 'errorCode': 0, 'IsSkipRecord': False}, {'contractAccountNumber': '<MASKED>', 'meterReadValue': '12051', 'meterSerialNumber': '<MASKED>', 'ActualMeterSerialNo': '<MASKED>', 'ReadingDate': None, 'ReadingWeekOfYear': None, 'ReadingMonth': 'Apr  2024', 'ReadingMonthOfYear': None, 'meterReadTimestamp': '2024-04-25T19:00:00', 'synthesisedFlag': 'N', 'consumption': 0.006, 'IsSynthesised': False, 'errorCode': 0, 'IsSkipRecord': False}, {'contractAccountNumber': '<MASKED>', 'meterReadValue': '12058', 'meterSerialNumber': '<MASKED>', 'ActualMeterSerialNo': '<MASKED>', 'ReadingDate': None, 'ReadingWeekOfYear': None, 'ReadingMonth': 'Apr  2024', 'ReadingMonthOfYear': None, 'meterReadTimestamp': '2024-04-25T20:00:00', 'synthesisedFlag': 'N', 'consumption': 0.007, 'IsSynthesised': False, 'errorCode': 0, 'IsSkipRecord': False}, {'contractAccountNumber': '<MASKED>', 'meterReadValue': '12058', 'meterSerialNumber': '<MASKED>', 'ActualMeterSerialNo': '<MASKED>', 'ReadingDate': None, 'ReadingWeekOfYear': None, 'ReadingMonth': 'Apr  2024', 'ReadingMonthOfYear': None, 'meterReadTimestamp': '2024-04-25T21:00:00', 'synthesisedFlag': 'N', 'consumption': 0.0, 'IsSynthesised': False, 'errorCode': 0, 'IsSkipRecord': False}, {'contractAccountNumber': '<MASKED>', 'meterReadValue': '12058', 'meterSerialNumber': '<MASKED>', 'ActualMeterSerialNo': '<MASKED>', 'ReadingDate': None, 'ReadingWeekOfYear': None, 'ReadingMonth': 'Apr  2024', 'ReadingMonthOfYear': None, 'meterReadTimestamp': '2024-04-25T22:00:00', 'synthesisedFlag': 'N', 'consumption': 0.0, 'IsSynthesised': False, 'errorCode': 0, 'IsSkipRecord': False}, {'contractAccountNumber': '<MASKED>', 'meterReadValue': '12063', 'meterSerialNumber': '<MASKED>', 'ActualMeterSerialNo': '<MASKED>', 'ReadingDate': None, 'ReadingWeekOfYear': None, 'ReadingMonth': 'Apr  2024', 'ReadingMonthOfYear': None, 'meterReadTimestamp': '2024-04-25T23:00:00', 'synthesisedFlag': 'N', 'consumption': 0.005, 'IsSynthesised': False, 'errorCode': 0, 'IsSkipRecord': False}], 'current_cost': 0.1781090000000018}

widget in energy dashboard
![image](https://github.com/pantherale0/haanglianwater/assets/5358625/5f2f7d53-4595-454b-8f22-13ff7baa63fd)

Anglian webUI
![image](https://github.com/pantherale0/haanglianwater/assets/5358625/2597fe73-c4a0-4424-a5b9-469508f043ed)

I believe we can agree that what is extracted from the API is correctly logged in HA but the data from the Anglian web is completely different to what is is actually returned from the API

**Comment by collse** [comment]
does your contractAccountNumber match your account# in the app or webui? as mine doesnt ...

**Comment by collse** [comment]
could it be you hardcoded an account ID?

https://github.com/pantherale0/pyanglianwater/blob/c5c1b939094c23c9c9d6fd0de18c679b3c233a70/pyanglianwater/api.py#L136

this is the contractAccountNumber I see in my readings

**Comment by collse** [comment]
ok, I removed the integration from my test instance. edited the api.py and replaced what I assumed to be the account number with my actual account number:

anglian webui
![image](https://github.com/pantherale0/haanglianwater/assets/5358625/7657b1d2-f2dd-43ee-b246-3088ec05bacc)

energy dashboard now
![image](https://github.com/pantherale0/haanglianwater/assets/5358625/fce83747-b822-4a09-a775-52cd88188ee6)

I believe there is an issue in your api - it seems it should be a timecode but its actually the account# that is used throughout

**Comment by pantherale0** [comment]
That is absolutely shocking behaviour, thank you for digging, I had thought it was a timestamp but perhaps not.

Will release an update asap.

**Comment by collse** [comment]
> I've reported to AW, as an urgent matter. Based on what we're seeing, I've informed that anyone with an active account at AW, could potentially change that `ts` header, and pull someone else's data.
> 
> Can't thank you enough for digging and finding this out!

no worries, I was sure there was something wrong and when I looked at my data and saw the different indicators I knew something was off and then I started digging and eventually looked at the api as I couldnt find anything in the component itself

**Comment by pantherale0** [comment]
@collse - going to close this, fixed in the module in latest release. API is not available for proper testing yet hence released as beta.
