### ISSUE TITLE
Error When Selecting Standard Tariff

### ISSUE THREAD

**Issue by strickersuk** [pantherale0/haanglianwater#22]
### System Health details

Good

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

When setting up the integration and selecting standard tariff it gives an error of float required for the custom water rate.

### Reproduction steps

As above.

### Debug logs

```text
Will post if required.
```

**Comment by collse** [comment]
just add anything, when selecting standard it doesnt take any custom rate and it will work as designed

**Comment by strickersuk** [comment]
Thanks, sounds like a quick tweak of the Readme will resolve this issue?

**Comment by pantherale0** [comment]
I will update the config flow sometime this evening, not a breaking bug at the moment so hasn't been a focus point of mine.

**Comment by strickersuk** [comment]
Appreciate your efforts in writing it in the first place. Thanks.
