### ISSUE TITLE
What do I fill in?

### ISSUE THREAD

**Issue by Croft5** [pantherale0/haanglianwater#27]
### System Health details

Hi,  I have followed your instructions and have come to a window with 5 boxes. The top 2 are blank, the 3rd has an eye. The 4th says standard and the 5th says 2.0954  GBP. What do I put in the first 3 lines?
![Anglian Water](https://github.com/pantherale0/haanglianwater/assets/54182221/7089fc06-fdcb-4a51-addc-ae12f96e72df)

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

As above

### Reproduction steps

1.
2.
3.
...
As above

### Debug logs

```text
As above
```

### Diagnostics dump

As above

**Comment by pantherale0** [comment]
Hi,

This looks like an issue with HA picking up the translations. What language is your system/user set to?

**Comment by Croft5** [comment]
English

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by pantherale0** [comment]
Force a refresh in your browser (ctrl + F5) and try again.

**Comment by Croft5** [comment]
Will do

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by pantherale0** [comment]
For reference:

![SmartSelect_20240615_173229_Home Assistant](https://github.com/pantherale0/haanglianwater/assets/7346615/c5cf2a6d-8e55-499c-9f43-0641d78e2646)

**Comment by Croft5** [comment]
That's very helpful, thanks.
I can do username and password.
What is Device ID?

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by pantherale0** [comment]
Device ID can be ignored. AW requires a device registration to your AW account before the usage data can be accessed. This just allows me to skip the registration step by using one I've already got during testing and make sure I don't "misuse" the service.

This is automatically generated in the background (16bit hex string if I remember correctly), I don't think the API will accept a custom string like "home assistant".

**Comment by Croft5** [comment]
I will give this a go and let you know. Thank you,
David

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Croft5** [comment]
Hi Jordan,

It’s all working 😊

Under the Water Tariff box can I set it as Liters or is it best to leave in cubic meters?
Also, I wonder what I should enter in the cost box, how much I pay per cubic meter, or a combination of the water and sewerage?
For me the cost per cubic meter is £1.68.53 and the sewerage is £1.71, so a total of around £3.40 per M3.

***@***.***

Yesterday I used 406L, so its bang on 😊

Dave

**Comment by pantherale0** [comment]
If you have selected a standard tariff, you can't change the rate. Likely you are on a different tariff if that is your rate.

LITE is the only tariff currently that will allow an overriden rate. The rest use whatever AW have published for the current financial year.

You cannot change to litres, the unit is hard coded. You can create a template sensor if you like to convert, but to be honest I built this integration more for the energy dashboard than anything else as the readings aren't frequent enough to be reliable in the sensor. The energy dashboard will show in litres anyway.

There are some issues with the cost calculation though on the energy dashboard which I think I've found the problem, just need to figure out the best way to fix.

**Comment by Croft5** [comment]
Hi Jordan,

Understood and in the HA energy dashboard it shows in Liters.
It's all working well.

It has imported back to 11th June, where it has a big amount, might that be the cumulative amount back to some point in time?
***@***.***

I now understand that I should use Standard, thanks.

Dave

**Comment by pantherale0** [comment]
```
It has imported back to 11th June, where it has a big amount, might that be the cumulative amount back to some point in time?
```

There is probably more usage prior to that date on your account, or that was the opening reading on the account. If you have taken over a supply (aka moved in), you will see readings from the first day that you have moved in as AW won't send back data from before this time.

If you haven't moved though, it's probably just because there is more data before that date and the large reading you see is based off the reading it pulled through.

**Comment by Croft5** [comment]
Hi Jordan,

Been here over 20 years 😊 we just had a smart meter fitted and it only went live a few days ago, took around a week to kick into life.
My guess is that its previous water usage all put together.

Thanks, Dave

**Comment by Croft5** [comment]
Hi Jordan,

The first time I installed and set up the Anglian Water integration it showed historical readings, back to when the smart meter started working (5 days ago).
I played around with things by uninstalling and reinstalling your integration. I did not fully understand the functions of those 5 boxes, but do now 😊
It is now back as it was originally, but I am not now seeing the historic data. It is showing yesterday but nothing earlier.
Is there something I need to do to clear everything for a fresh start or to force it to go get the historic data again?

Thanks, Dave

**Comment by pantherale0** [comment]
Hi Dave,

You need to use the `force_refresh_statistics` service call to force a refresh of previous data.

You cannot delete the statistics from the database currently as it's not supported by Home Assistant itself. There are some workarounds in the forums but will involve jumping into the database directly and deleting the rows with some SQL.

**Comment by Croft5** [comment]
OK, how do I do that?  😊

Dave

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
