### ISSUE TITLE
unable to load

### ISSUE THREAD

**Issue by 42digger** [pantherale0/haanglianwater#30]
## System Information

version | core-2024.5.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.6.25-haos
arch | x86_64
timezone | Europe/London
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1391
Downloaded Repositories | 12
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.2
-- | --
update_channel | stable
supervisor_version | supervisor-2024.06.0
agent_version | 1.6.0
docker_version | 25.0.5
disk_total | 28.6 GB
disk_used | 13.2 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Advanced SSH & Web Terminal (17.0.1), Studio Code Server (5.15.0), File editor (5.8.0), Mosquitto broker (6.4.0), SQLite Web (4.1.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 8
views | 15
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 7 June 2024 at 22:13
-- | --
current_recorder_run | 17 June 2024 at 21:27
estimated_db_size | 2610.78 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

i have followed the instructions
copied initial stable version files and folder into anglian_water folder
restarted HA
please wait starting configuration wizard for Anglian Water
then
Error
config flow could not be loaded: 500 internal server error server got itself in trouble

### Reproduction steps

1.as issue description
2.
3.
...

### Debug logs

```text
Logger: homeassistant.util.package
Source: util/package.py:123
First occurred: 21:29:33 (3 occurrences)
Last logged: 21:29:50

Unable to install package pyanglianwater==0.1.1: ERROR: Could not find a version that satisfies the requirement pyanglianwater==0.1.1 (from versions: 0.3.0, 0.3.1) ERROR: No matching distribution found for pyanglianwater==0.1.1
```

**Comment by pantherale0** [comment]
Hi,

Original versions are non-existent due to a security issue.

You should use the latest version available.

Thanks.
