### ISSUE TITLE
fails to set up 

### ISSUE THREAD

**Issue by 42digger** [pantherale0/haanglianwater#31]
## System Information

version | core-2024.6.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.6.33-haos
arch | x86_64
timezone | Europe/London
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4993
Installed Version | 1.34.0
Stage | running
Available Repositories | 1391
Downloaded Repositories | 12
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.4
-- | --
update_channel | stable
supervisor_version | supervisor-2024.06.0
agent_version | 1.6.0
docker_version | 26.1.4
disk_total | 28.6 GB
disk_used | 13.7 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Advanced SSH & Web Terminal (17.0.1), Studio Code Server (5.15.0), File editor (5.8.0), Mosquitto broker (6.4.0), SQLite Web (4.1.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 8
views | 15
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 9 June 2024 at 21:26
-- | --
current_recorder_run | 19 June 2024 at 23:34
estimated_db_size | 2707.32 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

2024-06-19 22:52:21.318 DEBUG (MainThread) [pyanglianwater.api] >> Request to login successful.
2024-06-19 22:52:22.128 DEBUG (MainThread) [pyanglianwater.api] >> Request to get_usage_details successful.
2024-06-19 22:52:22.783 DEBUG (MainThread) [pyanglianwater.api] >> Request to get_usage_details successful.
2024-06-19 22:52:22.786 ERROR (MainThread) [custom_components.anglian_water] Unexpected error fetching anglian_water data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 315, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/anglian_water/coordinator.py", line 63, in _async_update_data
    await self.insert_statistics()
  File "/config/custom_components/anglian_water/coordinator.py", line 142, in insert_statistics
    previous_read = float(last_stats.get("sum", None))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: float() argument must be a string or a real number, not 'NoneType'
2024-06-19 22:52:22.789 DEBUG (MainThread) [custom_components.anglian_water] Finished fetching anglian_water data in 1.468 seconds (success: False)

### Reproduction steps

1.copied latest files
2.integration fails with invalid string argument 
3.keeps retrying
...Needs attention
b.w.h.lawton@gmail.com
No devices or entities
Failed setup, will retry: float() argument must be a string or a real number, not 'NoneType'

### Debug logs

```text
2024-06-19 22:52:21.318 DEBUG (MainThread) [pyanglianwater.api] >> Request to login successful.
2024-06-19 22:52:22.128 DEBUG (MainThread) [pyanglianwater.api] >> Request to get_usage_details successful.
2024-06-19 22:52:22.783 DEBUG (MainThread) [pyanglianwater.api] >> Request to get_usage_details successful.
2024-06-19 22:52:22.786 ERROR (MainThread) [custom_components.anglian_water] Unexpected error fetching anglian_water data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 315, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/anglian_water/coordinator.py", line 63, in _async_update_data
    await self.insert_statistics()
  File "/config/custom_components/anglian_water/coordinator.py", line 142, in insert_statistics
    previous_read = float(last_stats.get("sum", None))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: float() argument must be a string or a real number, not 'NoneType'
2024-06-19 22:52:22.789 DEBUG (MainThread) [custom_components.anglian_water] Finished fetching anglian_water data in 1.468 seconds (success: False)
```

## System Information

version | core-2024.6.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.6.33-haos
arch | x86_64
timezone | Europe/London
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4993
Installed Version | 1.34.0
Stage | running
Available Repositories | 1391
Downloaded Repositories | 12
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.4
-- | --
update_channel | stable
supervisor_version | supervisor-2024.06.0
agent_version | 1.6.0
docker_version | 26.1.4
disk_total | 28.6 GB
disk_used | 13.7 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Advanced SSH & Web Terminal (17.0.1), Studio Code Server (5.15.0), File editor (5.8.0), Mosquitto broker (6.4.0), SQLite Web (4.1.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 8
views | 15
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 9 June 2024 at 21:26
-- | --
current_recorder_run | 19 June 2024 at 23:34
estimated_db_size | 2707.32 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

**Comment by shotgun185** [comment]
is this being looked into as I'm having the exact same issue.not sure if its code or anglian water side.cheers

**Comment by pantherale0** [comment]
Apologies, should be fixed in 2024.7.0

**Comment by shotgun185** [comment]
Thanks, have tried it and getting the same error:
Failed setup, will retry: '<=' not supported between instances of 'float' and 'NoneType
Have deleted and reinstalled but with the same issue.cheers

**Comment by 1967maverick** [comment]
I have the exact same issues as above guys on 2024.7.0

Failed setup will retry ‘<=‘ not supported between instances of ’float’ and ‘None Type’

Hope you can rectify - Thanks!
John

**Comment by pantherale0** [comment]
Ok, please try again with 2024.7.1 (a release file is currently building)

**Comment by 42digger** [comment]
Jordan , Thank you , I assume
1 device
2 entities
Is correct
Regards Jeff

Sent from my mobile 🍏 device

________________________________

**Comment by shotgun185** [comment]
excellent all working now!! thank you
cheers Dan

**Comment by 1967maverick** [comment]
Thanks - brill - all working now
