### ISSUE TITLE
2024.8.0b0 fails to initialise - unsupported operand type

### ISSUE THREAD

**Issue by collse** [pantherale0/haanglianwater#46]
## System Information

version | core-2024.8.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.33-haos
arch | x86_64
timezone | Europe/London
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4558
Installed Version | 1.34.0
Stage | running
Available Repositories | 1387
Downloaded Repositories | 64

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.4
-- | --
update_channel | stable
supervisor_version | supervisor-2024.08.0
agent_version | 1.6.0
docker_version | 26.1.4
disk_total | 109.3 GB
disk_used | 47.3 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Samba share (12.3.2), Duck DNS (1.18.0), File editor (5.8.0), Glances (0.21.1), Log Viewer (0.17.0), Advanced SSH & Web Terminal (18.0.0), MariaDB (2.7.1), Vaultwarden (Bitwarden) (0.22.0), chrony (3.0.1), Samba Backup (5.2.0), Z-Wave JS UI (3.10.0), Zigbee2MQTT (1.39.1-1), Mosquitto broker (6.4.1), Nginx Proxy Manager (1.0.1), Studio Code Server (5.15.0), ESPHome (2024.7.3), Govee to MQTT Bridge (2024.07.13-82ddc6e9), Music Assistant Server (2.1.1), diyHue (2.0.14), Matter Server (6.4.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 56
views | 14
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 5 August 2024 at 22:37
-- | --
current_recorder_run | 8 August 2024 at 14:56
estimated_db_size | 1005.91 MiB
database_engine | mysql
database_version | 10.11.6

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

the beta integration now fails on an existing install with an error message

![image](https://github.com/user-attachments/assets/56edbed0-a037-486d-9584-0c97429b8f98)

### Reproduction steps

1. update to 2024.08.0b0
2. error will show
...

### Debug logs

```text
2024-08-08 15:05:45.962 ERROR (MainThread) [custom_components.anglian_water] Unexpected error fetching anglian_water data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/anglian_water/coordinator.py", line 63, in _async_update_data
    await self.insert_statistics()
  File "/config/custom_components/anglian_water/coordinator.py", line 127, in insert_statistics
    hourly_consumption_data = await self.client.get_usages(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyanglianwater/__init__.py", line 78, in get_usages
    output["cost"] += (self.current_tariff_rate / days_in_year(start.year)) * days(start, end)
                                                                              ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyanglianwater/__init__.py", line 17, in days
    return (e-s).days
            ~^~
TypeError: unsupported operand type(s) for -: 'datetime.date' and 'datetime.datetime'
2024-08-08 15:05:45.964 DEBUG (MainThread) [custom_components.anglian_water] Finished fetching anglian_water data in 1.689 seconds (success: False)
```

**Comment by pantherale0** [comment]
Sorry it took so long to get back to this. Should be resolved for 2024.10.0.

By 2025.1.0 I'd like to have figured out the API for their new app implement that, but dependant on my free time (which I don't have a lot of at the moment due to work).
