### ISSUE TITLE
no data

### ISSUE THREAD

**Issue by chriscatuk** [pantherale0/haanglianwater#66]
### System Health details

```
## System Information

version | core-2024.10.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.31-haos-raspi
arch | aarch64
timezone | Europe/London
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 5000
Installed Version | 2.0.1
Stage | running
Available Repositories | 1528
Downloaded Repositories | 5

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 13.2
-- | --
update_channel | stable
supervisor_version | supervisor-2024.10.3
agent_version | 1.6.0
docker_version | 27.2.0
disk_total | 116.5 GB
disk_used | 12.5 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | rpi5-64
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.15.0), Home Assistant Google Drive Backup (0.112.1), Matter Server (6.6.0), Let's Encrypt (5.2.3), UniFi Network Application (3.4.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 5
-- | --
resources | 0
views | 5
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 26 October 2024 at 10:23
-- | --
current_recorder_run | 2 November 2024 at 14:34
estimated_db_size | 240.46 MiB
database_engine | sqlite
database_version | 3.45.3

</details>
```

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

The integration gets no data at all.

Both with the latest version from HACS or by cloning the latest version of the main branch (is https://github.com/pantherale0/haanglianwater/commit/91f283ca8b2baff5bde59552fb725d97fc8e8890 today)

### Reproduction steps

1. enter no device ID. enter Login/password
2. select Anglian and standard tariff
3. wait

### Debug logs

```text
2024-11-02 15:32:29.604 DEBUG (MainThread) [pyanglianwater.api] >> Request to login successful.
2024-11-02 15:32:30.309 DEBUG (MainThread) [pyanglianwater.api] >> Request to get_usage_details successful.
2024-11-02 15:32:30.893 DEBUG (MainThread) [pyanglianwater.api] >> Request to get_usage_details successful.
2024-11-02 15:32:30.894 DEBUG (MainThread) [custom_components.anglian_water] Finished fetching anglian_water data in 1.289 seconds (success: True)
```
```


### Diagnostics dump

download diagnostics button in missing for this integration
the page shows

Sensors Previous Consumption: 0.0 m³
Previous Cost: £0.00

No logbook events found

debug log was enabled

**Comment by pantherale0** [comment]
Hi

The login and requests were successful, what does the AW app/website show?

**Comment by chriscatuk** [comment]
Hi, thanks

I have been in this house for a year. the website shows data you can expect for a year of occupation.

I am not sure which region I would be in, but I don't recognise any of the names so I chose Anglian. 
I'm in Braintree, Essex.

Regarding the house: It's a new build, I was the first owner. I have bills and daily usage.
Regarding my account: it's my second house with that account. Previous house was more than a year ago.

**Comment by pantherale0** [comment]
Hmmm, I wonder if its because your old house is still associated with your account (perhaps for historical billing purposes or similar) and the integration is using that by default. I'm not sure what the responses look like in this case.

Are you comfortable making manual API requests? If so, could you send a POST request to the following endpoint and follow below please?

`https://my.anglianwater.co.uk/mobile/api/Login`

Body of the request needs to be (replace username value with your email and password value with your password)

```
{
	"DeviceId": "dd7c8853855cd528",
	"Password": "....",
	"RememberMe": true,
	"UserName": "...."
}
```
Finally set these headers:

```
Content-Type: application/json
ApplicationKey: 2.7$1.9.3$Android$samsung$SM-N9005$11
Partnerkey: Mobile$undefined$undefined$dd7c8853855cd528$2.7$1.9.3$Android$samsung$SM-N9005$11
```

You should get a valid JSON response (200 OK and from the response body, status = `Success`)

Within the response there is a array of JSON objects stored under `Data` where your initial account information exists. A few questions about this list:

1. Do you have more than one JSON object within? Perhaps there might be two as you have been in two properties with your account.
2. Check the values of `PrimaryBPNumber` and `ActualBPNumber`, are these values different?
3. Also check the values of `ActualAccountNo` and `PrimaryAccountNumber` are these values also different?

Depending on what you find, I might have to change the integration's config wizard to make the BP number configurable (currently its set to use `PrimaryBPNumber` and `ActualAccountNo` and this can't be changed).

**Comment by chriscatuk** [comment]
1. There's only one object.
2. `PrimaryBPNumber` and `ActualBPNumber` are the same
3. `ActualAccountNo` and `PrimaryAccountNumber` are different

`PrimaryAccountNumber` = the previous house
`ActualAccountNo` = the current house

I does seem you already use the right values.

I can do more API requests for you if it helps.


Just wondering, does Device ID matter? I'm not sure what it is.

**Comment by pantherale0** [comment]
Ahhh, I was wrong! The primary account number is used! I will update the python module.

Offending line: https://github.com/pantherale0/pyanglianwater/blob/5f71e9d40068e9a49adf02e775b1924e4fac819e/pyanglianwater/api.py#L137

**Comment by pantherale0** [comment]
Also, device ID does not matter. Its uniquely generated during the initial integration configuration and really just registers a dummy device with your AW account. Normally its derived from the fingerprint of your phone, but I realised that you can send pretty much anything in here and it will register.

**Comment by pantherale0** [comment]
Ooops, closed a bit prematurely. But should be resolved in upstream library, will update this integration later on tonight.

**Comment by pantherale0** [comment]
2024.11.0 has just been released :100:

**Comment by chriscatuk** [comment]
thanks! it worked
it got all my past year of data

I installed it via GitHub clone in custom components folder.   When will you make it the official version so I can revert back to HACS?

**Comment by pantherale0** [comment]
It should already be released

https://github.com/pantherale0/haanglianwater/releases/tag/2024.11.0

**Comment by chriscatuk** [comment]
thanks, indeed with HACS it worked too.

I didn't understand why I one update behind before opening this PR. I thought it was related to https://github.com/pantherale0/haanglianwater/blob/main/hacs.json

but apparently not. All is well now.

**Comment by pantherale0** [comment]
Awesome stuff, the version string isn't stored in any of the files in the repo and is generated by GitHub actions instead (automatically when I push a tag).

Sometimes hacs takes a while to pickup on new updates. But you can force refresh repositories and integration information if needed.
