### ISSUE TITLE
Error when I run Anglian Water: Force Refresh Statistics

### ISSUE THREAD

**Issue by andrewcliffoutlook** [pantherale0/haanglianwater#73]
## System Information

version | core-2024.11.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.31-haos-raspi
arch | aarch64
timezone | Europe/London
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 4993
Installed Version | 2.0.1
Stage | running
Available Repositories | 1463
Downloaded Repositories | 41

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 7 December 2024 at 00:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | false
cloud_ice_servers_enabled | true
remote_server | eu-central-1-11.ui.nabu.casa
certificate_status | ready
instance_id | 06596e6908f04cbd8eeae351a515c8ed
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 13.2
-- | --
update_channel | stable
supervisor_version | supervisor-2024.11.3
agent_version | 1.6.0
docker_version | 27.2.0
disk_total | 457.7 GB
disk_used | 25.3 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Advanced SSH & Web Terminal (19.0.0), Samba share (12.3.2), Mosquitto broker (6.4.1), ESPHome (2024.10.3), Let's Encrypt (5.2.3), File editor (5.8.0), OLED System Monitor (2.3.0), Glances (0.21.1), Node-RED (18.1.1), Studio Code Server (5.17.3), JupyterLab (0.15.4), AppDaemon (0.16.7), HassOS I2C Configurator (0.14), OpenSpeedTest (v2.0.5), openWakeWord (1.10.0), Piper (1.5.2), Whisper (2.2.0), Matter Server (6.6.0), Speedtest (1.6.2), SQLite Web (4.2.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 8
-- | --
resources | 14
views | 13
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 19 October 2024 at 15:19
-- | --
current_recorder_run | 16 November 2024 at 17:47
estimated_db_size | 4737.87 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

<details><summary>Sonoff</summary>

version | 3.8.1 (ffa7e22)
-- | --
cloud_online | 1 / 1
local_online | 1 / 1

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

I have been using the Anglian Water: Force Refresh Statistics in an automation to update water usage which I show on my HA energy dashboard.  Without running this I am forced to restart HA to populate this information.  On upgrading to 2024.11.0 my automation now shows this error:

Logger: homeassistant.helpers.script.websocket_api_script
Source: helpers/script.py:526
First occurred: 14:31:48 (1 occurrences)
Last logged: 14:31:48

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: unsupported operand type(s) for -: 'datetime.datetime' and 'datetime.date'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 526, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 764, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 727, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/anglian_water/__init__.py", line 80, in force_refresh_statistics
    await coordinator.insert_statistics(
  File "/config/custom_components/anglian_water/coordinator.py", line 135, in insert_statistics
    hourly_consumption_data = await self.client.get_usages(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyanglianwater/__init__.py", line 78, in get_usages
    output["cost"] += (self.current_tariff_rate / days_in_year(start.year)) * days(start, end)
                                                                              ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyanglianwater/__init__.py", line 17, in days
    return (e-s).days
            ~^~
TypeError: unsupported operand type(s) for -: 'datetime.datetime' and 'datetime.date'

Is there a workaround to address this issue?

### Reproduction steps

1. Go to Developer tools
2. Select Actions
3. Choose Anglian Water: Force Refresh Statistics
4. Input to and from dates
5. Click on "Perform Action"

This results in an error

### Debug logs

```text
See file attached in diagnostics log as too long to paste in here
```

### Diagnostics dump

[home-assistant_anglian_water_2024-11-18T14-44-19.278Z.log](https://github.com/user-attachments/files/17802088/home-assistant_anglian_water_2024-11-18T14-44-19.278Z.log)
[home-assistant_2024-11-18T14-45-32.192Z.log](https://github.com/user-attachments/files/17802102/home-assistant_2024-11-18T14-45-32.192Z.log)

**Comment by pantherale0** [comment]
Hi,

Yes I've seen this too.

Working on a fix now.

**Comment by pantherale0** [comment]
2024.11.0 just released which should address this.
